server:
#port: 8040
  port: 8041
spring:
  application:
    name: microservice-gateway-zuul
  zipkin:
      base-url: http://localhost:8081
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5